In [5]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [8]:
np.random.seed(0)
np.random.rand(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [10]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [11]:
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [12]:
np.random.seed(2)
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])